export const INIT_FETCH_DATA = "INIT_FETCH_DATA";
export const SUCCESS_FETCH_DATA = "SUCCESS_FETCH_DATA";
export const FAIL_FETCH_DATA = "FAIL_FETCH_DATA";
export const SELECT_CARD = "SELECT_CARD";
export const ERROR_ATTEMPT = "ERROR_ATTEMPT";
export const SUCCESS_ATTEMPT = "SUCCESS_ATTEMPT";
