export const INIT_FETCH_DATA = "INIT_FETCH_DATA";
export const SUCCESS_FETCH_DATA = "SUCCESS_FETCH_DATA";
export const FAIL_FETCH_DATA = "FAIL_FETCH_DATA";

export const SELECT_CARD = "SELECT_CARD";
export const ERROR_ATTEMPT = "ERROR_ATTEMPT";
export const SUCCESS_ATTEMPT = "SUCCESS_ATTEMPT";
export const VALIDATE_ATTEMPT = "VALIDATE_ATTEMPT";

export const GAME_COMPLETED = "GAME_COMPLETED";
export const GAME_START = "GAME_START";

export const CHECK_USER_SETTINGS = "CHECK_USER_SETTINGS";
export const SET_USER_SETTINGS = "SET_USER_SETTINGS";
export const UPDATE_USERNAME = "UPDATE_USERNAME";
